routes/web.php
<?php
Route::get('/', 'User\PageController@home')->name('welcome');
Auth::routes();
Route::namespace('User')->middleware(['auth'])->group(function() {
	Route::get('/profile', 'PageController@profile')->name('user.profile');
	Route::get('/profile/update', 'PageController@updateProfile')->name('user.profile.update');
	Route::post('/avatar/update', 'AuthorizeUserController@avatar')->name('user.avatar.store');
	Route::post('/cover/update', 'AuthorizeUserController@cover')->name('user.cover.store');

	Route::get('/profile/{anonymous}', 'PageController@anonymous')->name('user.profile.anonymous');
	Route::get('/user/{user}/profile', 'AnomonusUserController@show')->name('user.anonymous.json');
	Route::post('/user/{user}/rate', 'AnomonusUserController@rate')->name('user.rate.store');

	Route::get('/authorize_info', 'AuthorizeUserController@userInfo')->name('user.auth.info');
	Route::get('/posts', 'PostController@index')->name('post.index');
	Route::post('/post/store', 'PostController@store')->name('post.store');
	Route::get('/basicInfo', 'ProfileController@show');
	Route::resource('/works', 'WorkController');
	Route::resource('/educations', 'EducationController');
	Route::resource('/socials', 'SocialController');
	Route::resource('/awards', 'AwardController');
	Route::get('/available_links', 'SocialController@available')->name('social.set.links');

	Route::get('/network', 'PageController@network')->name('user.profile.network');
	Route::post('/network/{user}/store', 'NetworkController@store')->name('user.network.store');
	Route::get('/authorize_user_network_json', 'NetworkController@index');

	Route::get('/groups', 'GroupController@index')->name('user.groups');
	Route::post('/groups/join', 'GroupController@join')->name('user.group.join');
	Route::get('/group/{group}', 'GroupController@show')->name('user.groups.show');
	Route::get('/groups_json', 'GroupController@allGroup')->name('groups.json');
	Route::get('/group_json', 'GroupController@groupInfo')->name('group.info.json');
	Route::get('/group/{group}/post_json', 'GroupController@groupPost')->name('user.groups.posts');
	Route::get('/user_groups_json', 'GroupController@userAllGroup')->name('user.groups.json');
	Route::Post('/group/{group}/post_store', 'GroupController@store')->name('group.post.store');

});
/*|=====| User guest routes |==============*/

/*|=====| Admin guest routes |==============*/
Route::namespace('Auth')->group(function() {
	Route::get('/admin/login', 'Admin\LoginController@show')->name('admin.login.show');
	Route::post('/admin/login', 'Admin\LoginController@loginStore')->name('admin.login.store');
});
Route::namespace('Admin')->middleware(['auth:admin'])->prefix('admin')->group(function() {
	Route::get('/dashboard','PageController@dashboard')->name('admin.dashboard');
	Route::get('/users', 'UserController@index')->name('admin.user.all');
	Route::get('/blocked_users', 'UserController@blokedUser')->name('admin.user.blocked');
	Route::get('/user/{user}/block', 'UserController@index')->name('admin.user.store.block');
	Route::post('/user/{user}/waring', 'UserController@blockStore')->name('admin.user.warning.store');
	Route::post('/user/{user}/block', 'UserController@blockStore')->name('admin.user.block.store');

	Route::resource('/groups', 'Group\AdminGroupController');
	Route::get('/groups_json_paginate', 'Group\AdminGroupController@groups');
	Route::get('/groups_json_parent', 'Group\AdminSubGroupController@parentGroups');
	Route::get('/child_groups_json', 'Group\AdminSubGroupController@childGroup');
	Route::resource('/sub_groups', 'Group\AdminSubGroupController');

	Route::resource('/emergency-service','Emergency\ContactController')->except('show','edit');
	Route::post('/emergency-contact/store','Emergency\ContactController@contactStore')->name('emergency.contact.store');
	Route::get('/emergency/{service}/contact','Emergency\ContactController@allContact')->name('emergency.contact.all');
	Route::get('/training/user_search', 'Training\MamberController@allUserSearch');
	Route::resource('/training', 'Training\TrainingController');
	Route::resource('/training/{training}/members', 'Training\MamberController');
});

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/admin/login', 'AdminLoginController@showLoginForm')->name('admin.login');
// Route::post('/admin/login', 'AdminLoginController@login')->name('admin.login.submit');
// Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
// Route::get('/users', 'UserController@all');

app/Http/Controllers/Admin/Training/MamberController.php
<?php

namespace App\Http\Controllers\Admin\Training;

use App\Http\Controllers\Controller;
use App\Query\Admin\Training\Training;
use App\Query\Admin\Training\TrainingUser;
use App\Query\Auth\User;
use Illuminate\Http\Request;

class MamberController extends Controller
{
    public function index(Training $training)
    {
    	$training = $training->load('users.basicInfo');
    	return view('admin.training.members', compact('training'));
    }

    public function allUserSearch(Request $request)
    {
		// if($request->ajax()){
	    	$users = User::where('email','LIKE','%'.$request->search."%")
	    	    ->with('fullName')
	    	    ->get();
	    	// $users['name'] = $users->basicInfo->first_name. ' ' . $users->basicInfo->last_name;
	    	return $users;
		// }
    }
}

app/Http/Controllers/Admin/Training/TrainingController.php
<?php

namespace App\Http\Controllers\Admin\Training;

use App\Http\Controllers\Controller;
use App\Query\Admin\Training\Training;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TrainingController extends Controller
{
	private $training;

	public function __construct(Training $training)
	{
		$this->training = $training;
	}


    public function index()
    {
    	$trainings = $this->training->with('users')->orderBy('created_at','desc')->paginate(30);
    	// return $trainings;
    	return view('admin.training.training', compact('trainings'));
    }

    public function store(Request $request)
    {
    	$this->validate($request,[
    		'name' => 'required|max:200',
    		'logo' => 'nullable|max:2000|image'
    	]);
    	$image = null;
    	if($request->file('logo')) {
    		$image = Storage::disk('public')->put('admin/training', $request->file('logo'));
    	}
    	$this->training->create([
    		'name' => $request->input('name'),
    		'logo' => $image,
    	]);
    	return back()->with('success','training store successfully');
    }
}

resources/views/admin/training/members.blade.php
@extends('layouts.aapp')

@section('title')
	Traning
@endsection

@section('css')
<style>
	.btn-area {
		position: relative;
		margin-top: -15px;
		padding-bottom: 15px;
	}
	.memberAddInput{
		width: 82%;
	    border-radius: 0;
	}
	.memberAddBtn {
		position: absolute;
	    right: 0px;
	    top: 0px;
	    padding: 7px 21px;
	    border-radius: 0;
	}
</style>
@endsection

@section('content')
	@include('include.flash')
	<!-- GROUP-LIST -->
	<div class="info-container-top margin-bottom">
		<div class="row">
			<div class="col-sm-8">
				<ol class="breadcrumb">
					<li><a href="#">Home</a></li>
					<li><a href="#">Library</a></li>
					<li class="active">Data</li>
				</ol>
			</div>
		</div>
	</div>
	<div id="emergency-service" class="info-container">

	<div class="training_hint">
		<h4 class="text-info">Training : <b>{{ $training->name }}</b></h4><br>
	</div>
	<div class="row">
		<div class="col-sm-4"><b>Training Users</b></div>
		<div class="col-sm-8 text-right">
			<admin-user-search></admin-user-search>
		</div>
	</div><hr>
	<!-- INFO-TABLE -->
	<div class="info-table table-responsive">
		@if($training->users->count() > 0)
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Email</th>
					<th>UserName</th>
					<th>phone</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach($training->users as $key=>$member)
				<tr>
					<td>{{ $key+1 }}</td>
					<td>{{ $member->basicInfo->first_name.' '.$member->basicInfo->last_name }}</td>
					<td>{{ $member->email }}</td>
					<td>{{ $member->user_name?:'-' }}</td>
					<td>{{ $member->phone?:'-' }}</td>
					<td>
						<a href="#" class="btn btn-success btn-xs">Edit</a>
						<a href="#" class="btn btn-danger btn-xs">
							<i class="fa fa-window-close"></i>
						</a>
					</td>
				</tr>
				@endforeach	
			</tbody>
		</table>
		@else
			<div class="alert alert-info">No Training</div>
		@endif
	</div>
	</div>

@endsection
@section('js')
@endsection

resources/views/admin/training/training.blade.php
@extends('layouts.aapp')

@section('title')
	Traning
@endsection

@section('css')

@endsection

@section('content')
	@include('include.flash')
	<!-- GROUP-LIST -->
	<div class="info-container-top margin-bottom">
		<div class="row">
			<div class="col-sm-8">
				<ol class="breadcrumb">
					<li><a href="#">Home</a></li>
					<li><a href="#">Library</a></li>
					<li class="active">Data</li>
				</ol>
			</div>
			<div class="col-sm-4 text-right">
				<div class="btn-area">
					
					<button data-toggle="modal" data-target="#tranignCreateModal" class="btn btn-sm btn-primary">
						<i class="fa fa-plus" aria-hidden="true"></i> Create Traning</button>
				</div>
			</div>
		</div>
	</div>
	<div id="emergency-service" class="info-container">
	<!-- INFO-TABLE -->
	<div class="info-table table-responsive">
		@if($trainings->count() > 0)
		<table class="table table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Logo</th>
					<th>Trainee</th>
					<th>Create</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				@foreach($trainings as $key=>$training)
				<tr>
					<td>{{ $key+1 }}</td>
					<td>{{ $training->name }}</td>
					<td><img src="/storage/{{ $training->logo }}" width="40" alt="{{ $training->name }}"></td>
					<td>{{ $training->users->count() }}</td>
					<td>{{ Carbon\Carbon::parse($training->created_at)->toFormattedDateString() }}</td>
					<td>
						<a href="{{ route('members.index',$training) }}" class="btn btn-primary btn-xs">Members</a>
						<a href="#" class="btn btn-success btn-xs">Edit</a>
						<a href="#" class="btn btn-danger btn-xs">
							<i class="fa fa-window-close"></i>
						</a>
					</td>
				</tr>
				@endforeach	
			</tbody>
		</table>
		@else
			<div class="alert alert-info">No Training</div>
		@endif
	</div>
	<!-- /INFO-TABLE -->
	<!-- EM-CONTACT MODAL -->
	<div class="modal fade" id="tranignCreateModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">×</span>
					</button>
					<h5 class="modal-title" id="warningModalLabel">New Training</h5>
				</div>
				<div class="modal-body">
					<form enctype="multipart/form-data" action="{{ route('training.store') }}" method="post">
						{{ csrf_field() }}
						<div class="row form-group {{ $errors->has('name')?'has-error':'' }}">
							<label class="col-sm-4 text-right" for="servie"><b>Training name</b></label>
							<div class="col-sm-8">
								<input type="text" class="form-control" placeholder="training Nmae" name="name">
								@include('include.formErrorText',['inputName' => 'name'])
							</div>
						</div>
						<div class="row form-group {{ $errors->has('logo')?'has-error':'' }}">
							<label class="col-sm-4 text-right" for="servie"><b>Training Logo</b></label>
							<div class="col-sm-8">
								<input type="file" class="form-control" placeholder="training Nmae" name="logo">
								@include('include.formErrorText',['inputName' => 'logo'])
							</div>
						</div>
						<div class="row form-group">
							<div class="col-sm-4 text-right"></div>
							<div class="col-sm-8">
								<button type="submit" class="btn btn-sm btn-primary">
									<i class="fa fa-cloud"></i> Store Training
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	</div>

@endsection
@section('js')
<script>
@if($errors->all())
	$('#tranignCreateModal').modal('show');
@endif
</script>
@endsection